branch-defaults:
  default:
    environment: Project02-Filter-Image-Service-dev
    group_suffix: null
deploy:
  artifact: ./www/Filter-Image-Archive.zip
environment-defaults:
  Project02-Filter-Image-Service-dev:
    branch: null
    repository: null
global:
  application_name: Project02-Filter-Image-Service
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js 16 running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
